import "Photo.idl";

namespace PhotoEditor
{
    runtimeclass DetailPage : Windows.UI.Xaml.Controls.Page
    {
        DetailPage();
        Photo Item;
        void ResetColorEffects();
        void ResetLightEffects();
        void ResetBlurEffects();
        void ResetSepiaEffects();
        void FitToScreen();
        void ShowActualSize();
        void UpdateZoomState();
        void UpdateEffectBrush(String var);
        void ResetEffects();
    }
}