

namespace PhotoEditor
{
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainPage();
        Windows.Foundation.Collections.IVector<IInspectable> photos{ get; };
        Windows.Foundation.IAsyncAction start_connected_animation_for_back_navigation();
    }
}